### ISSUE TITLE
Less an issue more just a question

### ISSUE THREAD

**Issue by ParchmentWolf** [oleg-shilo/cs-script.core#14]
Sorry to make this post when you have other things to do. I was just wondering if the VB scripts support that was in the 'cs-script' was not supported by the core version (There's obviously a lot of differences in the structure just browsing through the intellisense listings). If not, is there plans to support it in the future? Thanks for your time.

**Comment by oleg-shilo** [comment]
OK, VB support is not there. I just was not sure about the demand. 

But the good news is that I had a quick run through the implementation and already managed to add support for stand alone executable. I only need now to extend it to the CS-ScriptLib.

Thus it is coming and in fact very soon. Probably a matter of days.

**Comment by ParchmentWolf** [comment]
Oh! Well, I cant speak for the 'current' demand... I know most people would ignore this wonderful softwares existance in the VB world simply cause it has C# in the name... Though I am making a mmorpg engine in .net and the server side has scripting using this and I know a decent sized group of VB coders that would love to use it provided VB was supported :D so it surely would not be wasted effort.

**Comment by oleg-shilo** [comment]
Well, it's not that difficult to extend. Even though .NET Core is missing the old nice CodeDOM based CSharpCompiler.

So I thought "Why not?"

**Comment by ParchmentWolf** [comment]
Eh, id say any support is better than no support for any of the features -> Especially since Core is the future! Thanks for making this thing even exist its one of the coolest tools I could imagine using.

**Comment by oleg-shilo** [comment]
Need some VB syntax help.

How one sets assembly attribute in VB?

```C#
// C#
[assembly: System.Reflection.AssemblyDescriptionAttribute("<whatever>")]
```

``` VB
' VB
????
```

**Comment by oleg-shilo** [comment]
An update. 

- Executing VB scripts with cscs.exe - done. Only waiting to an assembly attribute example before I can release.
- Executing VB scripts from managed host application - cannot be done. :( 
  Roslyn does not support VB and I am not sure if MS has any plans to bring it to life. Read here: https://github.com/dotnet/roslyn/issues/13523

**Comment by ParchmentWolf** [comment]
' VB
<Assembly: System.Reflection.AssemblyDescriptionAttribute("whatever")>

**Comment by oleg-shilo** [comment]
Done. 
Please find the release here: https://github.com/oleg-shilo/cs-script.core/releases/tag/v1.4.0.0

**Comment by ParchmentWolf** [comment]
Sweet!

**Comment by ParchmentWolf** [comment]
I've been out of the .net world for a while and came back to check out how this project was going.

In tryna find this original issues post, I found the roslyn repo has actual VB stuff now... Dunno of its really enough to have satisfied the requirement.

Has CsScript had any updates reguarding VB support?

**Comment by oleg-shilo** [comment]
Please be be aware that this repo is discontinued and its content moved to https://github.com/oleg-shilo/cs-script

As for VB, unfortunately VB syntax support is not available in .NET Core stream of CS-Script due to the insufficient popularity with developers.
