### ISSUE TITLE
Does cs-script.core still support C# debug? If yes, could you give the detailed steps?

### ISSUE THREAD

**Issue by yanglr** [oleg-shilo/cs-script.core#20]
**Environment of my PC**
OS Version: Windows 10 x64 (Windows_NT x64 10.0.19041)
.NET core version: 5.0.102
VSCode Version: 1.53.2 (system setup)

I installed cs-script.core using `choco install cs-script.core --pre`, then installed mono for Windows (version: mono-6.12.0.107-x64), I also installed below vs code extensions:
- C# (ms-dotnettools.csharp, Omisharp)
- C# Extensions (jchannon.csharpextensions)
- Mono debug extension
- CS-script extension

I can click "F1" to create new C# script, I can also run with clicking "Ctrl + F5", but debug does not work. Is this feature still in development? Thanks~

**Comment by oleg-shilo** [comment]
- Omnisharp - it is optional but very appropriate to have.
- C# Extensions - cannot comment on this one
- Mono debug extension - I would recommend uninstalling it as .NET core applications use .NDTE Core debugger. Mono can only interfere. But... it is up to you.
- CS-Script extension - you need it . Use the latest release v2.0.0.

![image](https://user-images.githubusercontent.com/16729806/108838620-00da2d80-7628-11eb-941a-8ad2669adb21.png)

"Ctrl + F5" - may or may not work depending on each ID key binding. To ensure you are can run/debug use toolbar:
![image](https://user-images.githubusercontent.com/16729806/108838812-44349c00-7628-11eb-8202-828bb3c32dc6.png)

Now enjoy your debugging :)

![debug](https://user-images.githubusercontent.com/16729806/108838856-53b3e500-7628-11eb-8979-9b464484afec.gif)

**Comment by yanglr** [comment]
OK, I will try. Thanks for your help.
