### ISSUE TITLE
Getting line of error when using the CompileCode method

### ISSUE THREAD

**Issue by alex1001xela** [oleg-shilo/cs-script.core#22]
Hey, hello there. I've been trying to get the line of an exception running in a script. I have been using the `CompileCode` method to generate an assembly.

When an exception is thrown in the script, I am able to catch it. But there is no info about the line of the error.

I have tried various permutations of `CSScript.EvaluatorConfig.DebugBuild = true`, `.WithEmitDebugInformation(true)`, and defining a PdbFile in the `CompileInfo` object, but I seem to miss something.

Is there an example of how I can make this work?

**Comment by oleg-shilo** [comment]
not sure
will check

**Comment by oleg-shilo** [comment]
OK, this is the test code that I checked:

```c#
CSScript.EvaluatorConfig.DebugBuild = true;

var asm = CSScript.CodeDomEvaluator
                    .CompileCode(@"using System;
                                    public class Script
                                    {
                                        public int Sum(int a, int b)
                                        {
                                            throw new Exception(""test"");
                                            return a+b;
                                        }
                                    }");

dynamic script = asm.CreateObject("*");

try
{
    var result = script.Sum(7, 3);
}
catch (Exception e)
{
    Console.WriteLine(e.StackTrace);
    return;
}
```
And this is the output it produces:

![image](https://user-images.githubusercontent.com/16729806/110944254-4f115f80-8390-11eb-82b6-c6ce7519fe3a.png)

As you can see it correctly reports the line 6 as the line that triggered the exception.

Try this sample on your environment.

**Comment by alex1001xela** [comment]
I think this would need some restructuring of our code, so I cannot test it immediately. But your example works, so we have a starting point. Thank you so much. :)

**Comment by oleg-shilo** [comment]
Please be aware that ~5 mins CS-Script release targeting .NET 5 has been published:
https://github.com/oleg-shilo/cs-script/releases/tag/v4.0.0.0
 
Choco and Nuget are yet to be updated. Then I will drop the "pre-release status". Note that CS-Script v4.0.0.0 is an equivalent of CS-Script.Core v2.0.0.0.

This means that now and in all future versions you will need access the CS-Script package via the name "CS-Script" not "CS-Script.Core".
