### ISSUE TITLE
Issue referring .cs file

### ISSUE THREAD

**Issue by Bukran** [oleg-shilo/cs-script.core#24]
Hi, Oleg.

Could you provide an example of a script referring a class from another .cs file? Or at least point me in the right direction?

I need to load a script in a hosted environment, this script sometimes needs to refer another .cs files (//css_inc) and also some DLLs (//css_ref). I know I've achieved this in NET Framework in the past but now I need to do it in NET Core 5.0.
Attached you can find a small sample project to show the difficulties I'm experiencing.

Thanks in advance.
[ConsoleApp3.zip](https://github.com/oleg-shilo/cs-script.core/files/6190759/ConsoleApp3.zip)

**Comment by oleg-shilo** [comment]
Hi Bukran
It is enough to change the evaluator to the CodeDom:
```C#
CSScript.CodeDomEvaluator.LoadFile<IDriver>(...)
```
Roslyn does not allow processing multi-file scripts. It is it's strongest limitation

**Comment by Bukran** [comment]
Thanks, Oleg.

I'll try `CodeDomEvaluator`. Is there a comparative chart of what can and cannot be done with both IEvaluators?

**Comment by oleg-shilo** [comment]
Not yet. 

I am in process of porting of this repository documentation in the CS-Script repo: https://github.com/oleg-shilo/cs-script. 
And sadly I am extremely behind with this task. But for CodeDom evaluator it is the latest feature of CS-Script that became available in the .NET Core stream only with the release of .NET 5. Thus it is yet to be documented.

To put it simple. `CSScript.CodeDomEvaluator` does exactly what `CSScript.RoslynEvaluator` does plus supports multi-file scripts. In fact it was the feature which triggered the whole CodeDomEvaluator effort.

Interestingly enough the comparative chart is available for the .NET Framework version: https://github.com/oleg-shilo/cs-script.net-framework/wiki/Choosing-Compiler-Engine#csscriptevaluator

But it is simply not applicable to .NETCore/.NET5 releases.
I will need to create this chart. It will be something close to this:


|Features            | CodeDom                   | Roslyn         |
|--- | --- | --- |
| Performance | good                |  good       |
| Debugging            | yes                  | yes              |
| C# 6 and higher support         | yes             | yes             |
| CS-Script directives | yes                 | no         |
| Top-level classes | yes                 | no         |
| Unloading support    | full                | full    |

**Comment by Bukran** [comment]
Thank you very much. This chart is enough for me at the moment.
