### ISSUE TITLE
Use different search dirs for each call

### ISSUE THREAD

**Issue by ArcticLampyrid** [oleg-shilo/cs-script.core#3]
Like
```c#
Assembly script1 = CSScript.Evaluator
                          .CompileCode("............", "D:\mylib1");
Assembly script2 = CSScript.Evaluator
                          .CompileCode("............", "D:\mylib2");
```

**Comment by oleg-shilo** [comment]
The usage of search dirs is intended to be configured globally:
```c#
CSScript.GlobalSettings.AddSearchDir("<your dir>");

dynamic script = CSScript.RoslynEvaluator
                         .ReferenceAssembly("System.ValueTuple")
                         . . .
```
But you can configure assemblies per call:
```C#
CSScript.Evaluator.ReferenceAssembly("asm_1")
                  .ReferenceAssembly("asm_2")
```

**Comment by ArcticLampyrid** [comment]
Is there any plan to support to use different search dirs for each evaluator without changing GlobalSettings?

**Comment by oleg-shilo** [comment]
> ...support to use different search dirs for each evaluator without changing GlobalSettings?

I think there is some confusion here. CS-Script does not support dedicated search dirs per `compile/load` calI. But it does per each evaluator. Though indirectly, via code content:

```c#
var code = "....";
Assembly script1 = CSScript.Evaluator
                           .ReferenceAssemblyFromCode(code, @"D:\mylib1")
                           .CompileCode(code);
```

And of course you can pack the code above in a little extension and achieve the desired syntax:
```C#
public static Assembly CompileCode(IEvaluator evaluator, string code, params string[] searchDirs)
    => evaluator.ReferenceAssembliesFromCode(code, searchDirs)
                .CompileCode(code);

. . . 

Assembly script1 = CSScript.Evaluator
                           .CompileCode("............", @"D:\mylib1");
Assembly script2 = CSScript.Evaluator
                           .CompileCode("............", @"D:\mylib2");
```

Though mind you that `ReferenceAssembliesFromCode` will analyze the **code** and try to reference the assemblies that are expressed in code (either with `using` or with `//css_ref`) and located in the specified `searhDirs`. Meaning that if you want to reference a specific assembly (that is not expressed in the code) then you will need to modify a bit your new `CompileCode` extension.

**Comment by ArcticLampyrid** [comment]
Is it useful for "//css_import"?

**Comment by oleg-shilo** [comment]
Please elaborate. Useful for what?

The intended use of `ReferenceAssemblyFromCode` is as below

```C#
var code = "....";
CSScript.Evaluator
        .ReferenceAssemblyFromCode(code, searchDirs)
        .CompileCode(code)

// or

CSScript.Evaluator
        .ReferenceAssemblyFromCode("//css_ref DataUtil.dll", searchDirs)
        .ReferenceAssemblyFromCode("//css_ref mySerialization.dll", searchDirs)
        .ReferenceAssemblyFromCode("//css_ref printing.dll", searchDirs)
        .CompileCode(code)

**Comment by ArcticLampyrid** [comment]
```c#
//css_import othercsfile.cs
```

**Comment by oleg-shilo** [comment]
Are you asking if `ReferenceAssemblyFromCode` processes `css_import` directives?

If indeed you are then the answer is no it does not. 
`ReferenceAssemblyFromCode` does exactly what names suggests. It references assemblies.

`//css_include` and `//css_import` are directives not for referencing assemblies but including extra scripts (C# source code). And they are not supported by the .NETCore evaluator simply because .NETCore (Roslyn scripting) does not support multifile scripting.

Meaning that you will need to combine your multiple scripts into one an pass it to the `CompileCode`

**Comment by oleg-shilo** [comment]
You are welcome
