### ISSUE TITLE
Learning to use CS-Script in a NET core application

### ISSUE THREAD

**Issue by Bukran** [oleg-shilo/cs-script.core#8]
Hi Oleg.

Is there any updated documentation to test CS-Script in a NET core application? I've used it in the past (NET Framework) but I'm experiencing some difficulties following the samples. I guess the reason is that they were not specifically written for cs-script.core.

Following https://github.com/oleg-shilo/cs-script/blob/master/Source/deployment/samples/Hosting/Scripting.evaluator.cs, for example:

CSScript.EvaluatorConfig.Engine cannot be set to any other but Roslyn.
CompileMethod_Instance throws RuntimeBinderException "cannot invoke a non-delegate type".
CSScript.Evaluator.LoadDelegate<T> returns a null reference.

Can you point me in the right direction? Thanks in advance.

[HostedScripting.zip](https://github.com/oleg-shilo/cs-script.core/files/4040174/HostedScripting.zip)

**Comment by oleg-shilo** [comment]
You are right, the Core API is a little different. And I did not realize that the release does not include any chm help nor code samples. I am making this issue into "enhancement" will try to address it soon.

As for your example this is the correct use of API:

```C#
dynamic script = CSScript.Evaluator
                         .CompileMethod(@"int add(int a, int b)
                                        {
                                            return a + b;
                                        }")
                        .CreateObject("*");

var result = script.add(1, 2);

dynamic calc = CSScript.Evaluator
                       .LoadMethod(@"int add(int a, int b)
                                        {
                                            return a + b;
                                        }");
result = calc.add(1, 3);


MethodDelegate<int> add = CSScript.Evaluator
                                  .CreateDelegate<int>(
                                                  @"int add(int a, int b)
                                                      {
                                                          return a + b;
                                                      }");
result = add(4, 5);

//  LoadDelegate throws NotImplemented exception as this scenario is not supported by Roslyn on .NTE Core
// You may want to consider using interfaces with LoadCode/LoadMethod or use CreateDelegate instead.

Func<int, int, int> add = CSScript.Evaluator
                                  .LoadDelegate<Func<int, int, int>>(
                                        @"int add(int a, int b)
                                          {
                                              return a + b;
                                          }");
result = add(4, 5);
```

**Comment by oleg-shilo** [comment]
As an immediate measure I have added this sectipn to the online documentation: https://github.com/oleg-shilo/cs-script.core/wiki/Hosting-Samples

**Comment by Bukran** [comment]
Thanks Oleg.

Every instruction returning a _dynamic_ object works (as shown in your first response).
Unfortunately, I cannot get to work interface aligment. LoadCode<T> and LoadMethod<T> both throw a NullReferenceException.

I've extended the test project.

[HostedScriptingv2.zip](https://github.com/oleg-shilo/cs-script.core/files/4053105/HostedScriptingv2.zip)

**Comment by oleg-shilo** [comment]
Thanks,
 Yes interface alignment is a problem on .NET Core That's why I was planing simply mark it as not implemented but... regretfully forgot to do so. 

However, after looking at the implementation I decided to a trick if interface injection directly in the decorated outer class for `LoadMethod<T>`.   It worked.

The very next release will have the issue addressed. 

As for `LoadCode<T>` you can still achieve the desired behavior but since I cannot do duck-typing on .NET Core the interface needs to be placed (mins its namespace) directly in the script code:
```C#
string code = @"using System;                            
                public class Script : ICalc
                {
                    public int Sum(int a, int b)
                    {
                        return a + b;
                    }
                }";

var script = CSScript.Evaluator.LoadCode<ICalc>(code);
int result = script.Sum(13, 2);
```

**Comment by Bukran** [comment]
LoadCode<T> works as expected if I the interface is explicitly indicated in the Script class.
And I look forward to hearing from next release in order to test LoadMethod<T>.

Thank you very much.

**Comment by oleg-shilo** [comment]
You can test the fix with the pre-release nuget package:
https://www.nuget.org/packages/CS-Script.Core/1.2.3.3-pre

**Comment by Bukran** [comment]
Positively tested, thanks!

**Comment by oleg-shilo** [comment]
I still need to close a few tasks for the stand alone engine and then will do the proper release. Will try to compile and release CSScripLib API help too.

**Comment by oleg-shilo** [comment]
Now I can close this issue :)

The current resources are:
- NuGet package with the code sample for all supported hosted scenarios:
  `Install-Package CS-Script.Core.Samples`
- Added API documentation help file: https://github.com/oleg-shilo/cs-script.core/releases
- Added API documentation web content: https://www.cs-script.net/cs-script.core/help
