### ISSUE TITLE
C#8 support

### ISSUE THREAD

**Issue by Bukran** [oleg-shilo/cs-script.core#9]
Hello,

Is C#8 supported? I intend to use CSScript.Evaluator.LoadFile<T> where T is an interface with a default method.

If C#8 is not available, the compiler obviously throws an exception: 'class does not implement interface member'.

Thanks in advance.

**Comment by oleg-shilo** [comment]
Hi Bukran, the specific syntax version is supported/unsupported not by CS-Script itself but by the underlying services - Roslyn.

This is the package responsible for the actual compilation:
![image](https://user-images.githubusercontent.com/16729806/72605789-8d201880-3971-11ea-8626-5fb5a2cd1269.png)

Thus you will need to ensure that you are using the package that can handle C#8 syntax. Unfortunately I cannot tell you which version of that package is. But probably if you google for Roslyn + C#8 then you may find some info.

**Comment by Bukran** [comment]
I think this issue has been solved after updating Microsoft.CodeAnalysis.CSharp.Scripting
